FROM node:@NODE_VERSION@

ENV FIREBASE_TOOLS_VERSION @FIREBASE_TOOLS_VERSION@ 
ENV TAG_VERSION @TAG_VERSION@ 

RUN set -eux; \
    yarn global add \
        firebase-tools@${FIREBASE_TOOLS_VERSION} \
        js-beautify \
        typescript \
        eslint \
        tslint \
    && firebase --version \
    && tsc --version \
    && eslint --version \
    && tslint --version

RUN set -eux; \
  mkdir /project
WORKDIR /project

COPY ./entrypoint.sh /
ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 5000

CMD ["firebase"]
